import Head from "next/head";
import Image from "next/image";
import Button from "../components/Button";
import styles from "../styles/Home.module.css";
import GitHub from "../components/Icons/GitHub";
import { loginWithGitHub } from "../firebase/client";
import { useEffect } from "react";
import { useRouter } from "next/router";
import useUser, { USER_STATES } from "../hooks/useUser";

export default function Home() {
  const user = useUser();
  const router = useRouter();

  useEffect(() => {
    user && router.replace("/home");
  }, [user]);

  const handleClick = () => {
    loginWithGitHub().catch((err) => {
      console.log(err);
    });
  };
  return (
    <>
      <Head>
        <title>Devtter 🐦 </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.innerHome}>
        <Image src="/bird.png" alt="logo" width={120} height={120} />
        <h1 className={styles.title}>Devter</h1>
        <h2 className={styles.subtitle}>
          Talk about developement <br /> with developers 👨‍💻 👩‍💻{" "}
        </h2>
        <div className={styles.buttonContainer}>
          {user === USER_STATES.NOT_LOGGED && (
            <Button onClick={handleClick}>
              <GitHub fill="#fff" width={24} height={24} />
              Login with GitHub
            </Button>
          )}
          {user === USER_STATES.NOT_KNOW && <img src="/spinner.gif" />}
        </div>
      </section>
    </>
  );
}
